# Configuration specific to product-service

# Server configuration
server.port=8085

# H2 Database configuration (default - development)
spring.datasource.url=jdbc:h2:mem:productdb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Logging
# logging.level.com.youssef.productms=DEBUG
logging.level.com.youssef.productservice=DEBUG
